### ISSUE TITLE
Bug: Missing python libs in KeyShot 13

### ISSUE THREAD

**Issue by hypnoboutique** [aws-deadline/deadline-cloud-for-keyshot#107]
### Expected Behaviour

Works

### Current Behaviour

Does not work

```
Traceback (most recent call last):
  File "<string>", line 9, in <module>
ModuleNotFoundError: No module named 'shlex'
```

![Screenshot 2024-08-22 at 09 58 55](https://github.com/user-attachments/assets/b448e636-cef0-405e-be73-a16e9256ae0d)

### Reproduction Steps

- Install Keyshot 13 on mac OS 14.5
- Follow (incorrect) install steps [here](https://github.com/aws-deadline/deadline-cloud-for-keyshot) (the script is not located at `deadline-cloud-for-keyshot/keyshot_submitter/Submit to AWS Deadline Cloud.py`, it is in `deadline-cloud-for-keyshot/src/deadline/keyshot_submitter/`)
- Attempt to submit from scripts panel in Keyshot

A number of python modules are missing in the Keyshot bundled version of python. Initially, as seen in my screenshot, this was shlex. I copied shlex, pathlib, zipfile from a local dist of python and was able to make something happen but still hit an error eventually because zlib wasn't available.

### Code Snippet

n/a

**Comment by hypnoboutique** [comment]
I finally got this script to complete by patching the missing libs and modules, modified my local version and shell profile (temporarily, I can't leave them like this). Now, after creating a job, every task fails with:

```
2024/08/22 14:28:30+01:00  
2024/08/22 14:28:30+01:00 ==============================================
2024/08/22 14:28:30+01:00 --------- Entering Environment: KeyShot
2024/08/22 14:28:30+01:00 ==============================================
2024/08/22 14:28:30+01:00 ----------------------------------------------
2024/08/22 14:28:30+01:00 Phase: Setup
2024/08/22 14:28:30+01:00 ----------------------------------------------
2024/08/22 14:28:30+01:00 Writing embedded files for Environment to disk.
2024/08/22 14:28:30+01:00 Mapping: Env.File.initData -> /sessions/session-7f2614ae86654595964452509e2687c5bx5_o9qe/embedded_filessp_jmspe/init-data.yaml
2024/08/22 14:28:30+01:00 Wrote: initData -> /sessions/session-7f2614ae86654595964452509e2687c5bx5_o9qe/embedded_filessp_jmspe/init-data.yaml
2024/08/22 14:28:30+01:00 ----------------------------------------------
2024/08/22 14:28:30+01:00 Phase: Running action
2024/08/22 14:28:30+01:00 ----------------------------------------------
2024/08/22 14:28:30+01:00 Running command sudo -u job-user -i setsid -w /sessions/session-7f2614ae86654595964452509e2687c5bx5_o9qe/tmp1ztvlm_m.sh
2024/08/22 14:28:30+01:00 Command started as pid: 2116
2024/08/22 14:28:30+01:00 Output:
2024/08/22 14:28:31+01:00 /sessions/session-7f2614ae86654595964452509e2687c5bx5_o9qe/tmp1ztvlm_m.sh: line 20: KeyShotAdaptor: command not found
2024/08/22 14:28:31+01:00 Process pid 2116 exited with code: 127 (unsigned) / 0x7f (hex)
```

Any suggestions would be gratefully received.

**Comment by crowecawcaw** [comment]
Thank you for the bug report. We were able to recreate the original issue and will work on a fix.

For the second issue, it looks like the adapter is not installed or not accessible on the worker. The Keyshot integration has two main components - the submitter which is the plugin in Keyshot you got working and the adapter which is a Python wrapper around Keyshot itself. The tasks that the submitter creates and which a worker pick up call the `KeyShotAdaptor` command which should start the adapter script. Have you already installed the adapter on your workers? Instructions [here](https://github.com/aws-deadline/deadline-cloud-for-keyshot).

**Comment by hypnoboutique** [comment]
Hi, 

Thanks for such a quick response 🙏 

It does indeed sound like I haven't installed the adaptor. I'm confused about how to do this, though, because the controls in Deadline Cloud feel really opaque to me, I can't see where to configure the workers, other than to give them more grunt.

Are the instructions you mention in the README applicable to Deadline Cloud? If so, could you give me a tiny steer as to where I can modify the image or whatever to ensure the adaptor is installed?

Many thanks!

**Comment by crowecawcaw** [comment]
Sure thing. Deadline Cloud has two types of fleets and workers - service managed fleets (SMF) and customer managed fleets (CMF). On SMF, Deadline manages the workers including scaling up and down and image configuration. SMF is simpler to use, has a a preconfigured image, and includes some software that's ready to go. On CMF, you bring your own compute platform such as EC2 or on-prem servers to Deadline which then handles the scheduling but does not manage the workers themselves or configure the software.

Currently, Keyshot is not available on SMF and only on CMF. To get Keyshot working, you'll need to set up your own CMF fleet, install Keyshot on it, and install the adapter. There is CMF setup documentation [here](https://docs.aws.amazon.com/deadline-cloud/latest/userguide/manage-cmf.html).

**Comment by hypnoboutique** [comment]
This makes a lot of sense. Thank you very much!

**Comment by joel-wong-aws** [comment]
Hello @hypnoboutique, we really appreciate the bug report! The README instructions have been updated to reflect the correct installation steps and the submitter has been updated to remove dependencies that aren't available in KeyShot Python. You can try out the updated submitter by copying `deadline-cloud-for-keyshot/src/deadline/keyshot_submitter/Submit to AWS Deadline Cloud.py` into your KeyShot scripts directory and overwriting the old version of the script.

**Comment by crowecawcaw** [comment]
Also, Deadline Cloud [released Windows SMF support today](https://aws.amazon.com/about-aws/whats-new/2024/08/aws-deadline-cloud-windows-server-2022-service-managed-fleets/) which includes built in Keyshot support. You can now create a simple Windows SMF fleet and submit jobs to it from this submitter to start rendering with a minimal amount of configuration and setup.

**Comment by crowecawcaw** [comment]
Closing this issue since it should be fixed. Feel free to open it if you still encounter errors with the latest version.

**Comment by hypnoboutique** [comment]
Thank you guys, I'll give it a whirl this evening. 🙏

**Comment by hypnoboutique** [comment]
It's working great with the new script and the Windows SMF 🎉 

Thank you so much for your help with this!
