### ISSUE TITLE
Bug: Unknown Error when rendering some scenes (regression?)

### ISSUE THREAD

**Issue by yuanmich2** [aws-deadline/deadline-cloud-for-keyshot#116]
### Expected Behaviour

I had succeeded in rendering this scene on Windows customer managed fleets on Deadline Cloud in the past, so I expected Windows serviced managed fleets to also succeed

### Current Behaviour

The renders crash. Here are the logs:

[Deadline Cloud Farm_Service Managed Jobs_session-c8b3f863b3514088a21ad20173289eea.log](https://github.com/user-attachments/files/16937428/Deadline.Cloud.Farm_Service.Managed.Jobs_session-c8b3f863b3514088a21ad20173289eea.log)

The important part seems to be this:
```
2024/09/09 15:46:18-07:00 ADAPTOR_OUTPUT: STDOUT: [W] "GPU Mode" "Unknown error!\nSee log for additional information."
2024/09/09 15:46:18-07:00 ADAPTOR_OUTPUT: STDOUT: [W] Rendering stopped!
2024/09/09 15:46:18-07:00 ADAPTOR_OUTPUT: STDOUT: [D] Enabling OS sleep
2024/09/09 15:46:18-07:00 ADAPTOR_OUTPUT: STDOUT: [D] Failure
2024/09/09 15:46:18-07:00 ADAPTOR_OUTPUT: STDOUT: [D] Exit? false 0
2024/09/09 15:46:18-07:00 ADAPTOR_OUTPUT: STDOUT: [W] Python errors:
2024/09/09 15:46:18-07:00 ADAPTOR_OUTPUT: STDOUT: Traceback (most recent call last):
2024/09/09 15:46:18-07:00 ADAPTOR_OUTPUT: STDOUT:   File "<string>", line 77, in <module>
2024/09/09 15:46:18-07:00 ADAPTOR_OUTPUT: STDOUT:   File "<string>", line 73, in main
2024/09/09 15:46:18-07:00 ADAPTOR_OUTPUT: STDOUT:   File "C:\ProgramData\Amazon\OpenJD\session-c8b3f863b3514088a21ad20173289eeavgqncv4t\.env\Lib\openjd\adaptor_runtime_client\base_client_interface.py", line 212, in poll
2024/09/09 15:46:18-07:00 ADAPTOR_OUTPUT: STDOUT:     self._perform_action(action)
2024/09/09 15:46:18-07:00 ADAPTOR_OUTPUT: STDOUT:   File "C:\ProgramData\Amazon\OpenJD\session-c8b3f863b3514088a21ad20173289eeavgqncv4t\.env\Lib\openjd\adaptor_runtime_client\base_client_interface.py", line 233, in _perform_action
2024/09/09 15:46:18-07:00 ADAPTOR_OUTPUT: STDOUT:     action_func(a.args)
2024/09/09 15:46:18-07:00 ADAPTOR_OUTPUT: STDOUT:   File "C:\ProgramData\Amazon\OpenJD\session-c8b3f863b3514088a21ad20173289eeavgqncv4t\.env\Lib\deadline\keyshot_adaptor\KeyShotClient\keyshot_handler.py", line 62, in start_render
2024/09/09 15:46:18-07:00 ADAPTOR_OUTPUT: STDOUT:     lux.renderImage(path=output_path, opts=opts, format=self.output_format_code)
2024/09/09 15:46:18-07:00 ADAPTOR_OUTPUT: STDOUT: Exception: Unknown error!
2024/09/09 15:46:18-07:00 ADAPTOR_OUTPUT: STDOUT: See log for additional information.
2024/09/09 15:46:18-07:00 ADAPTOR_OUTPUT: STDOUT: Unknown error!
```

### Reproduction Steps

The project file is too big to share, but I have a workstation with it that I'd be willing to share for debugging help. The scene is a random free keyshot project I found online.

I am using the latest submitter (0.2.1), Keyshot 2024, and Windows SMF

### Code Snippet

n/a

**Comment by yuanmich2** [comment]
Here's the project file I'm using broken up across a multi-part zip file. You have to rename the files as .zip.<number> instead of .zip.<number>.zip to get the files to extract properly.
[CoffeeShop.zip.001.zip](https://github.com/user-attachments/files/16937461/CoffeeShop.zip.001.zip)
[CoffeeShop.zip.002.zip](https://github.com/user-attachments/files/16937460/CoffeeShop.zip.002.zip)
[CoffeeShop.zip.003.zip](https://github.com/user-attachments/files/16937462/CoffeeShop.zip.003.zip)
[CoffeeShop.zip.004.zip](https://github.com/user-attachments/files/16937458/CoffeeShop.zip.004.zip)
[CoffeeShop.zip.005.zip](https://github.com/user-attachments/files/16937459/CoffeeShop.zip.005.zip)

**Comment by yuanmich2** [comment]
Update: I re-ran this job on CMF to confirm that it works, but I actually ended up with errors as well. The errors look similar but with no tracelog.
```
2024/09/12 12:03:10-07:00 ADAPTOR_OUTPUT: STDOUT: [I] Rendering: 0.0%
2024/09/12 12:03:31-07:00 ADAPTOR_OUTPUT: STDOUT: [W] "GPU Mode" "Unknown error!\nSee log for additional information."
2024/09/12 12:03:31-07:00 ADAPTOR_OUTPUT: STDOUT: [I] Applying image styles: 0.0%
2024/09/12 12:03:34-07:00 ADAPTOR_OUTPUT: STDOUT: [I] Saving Coffee-Shop.0_clown.png: 0.0%
2024/09/12 12:03:34-07:00 ADAPTOR_OUTPUT: STDOUT: [I] Saving Coffee-Shop.0_raw.exr: 0.0%
2024/09/12 12:03:35-07:00 ADAPTOR_OUTPUT: STDOUT: [I] Saving Coffee-Shop.0_label.exr: 0.0%
2024/09/12 12:03:35-07:00 ADAPTOR_OUTPUT: STDOUT: [I] Saving Coffee-Shop.0_ao.exr: 0.0%
2024/09/12 12:03:35-07:00 ADAPTOR_OUTPUT: STDOUT: [I] Saving Coffee-Shop.0_shadow.exr: 0.0%
2024/09/12 12:03:35-07:00 ADAPTOR_OUTPUT: STDOUT: [I] Saving Coffee-Shop.0_refraction.exr: 0.0%
2024/09/12 12:03:35-07:00 ADAPTOR_OUTPUT: STDOUT: [I] Saving Coffee-Shop.0_reflection.exr: 0.0%
2024/09/12 12:03:36-07:00 ADAPTOR_OUTPUT: STDOUT: [I] Saving Coffee-Shop.0_caustics.exr: 0.0%
2024/09/12 12:03:36-07:00 ADAPTOR_OUTPUT: STDOUT: [I] Saving Coffee-Shop.0_gi.exr: 0.0%
2024/09/12 12:03:36-07:00 ADAPTOR_OUTPUT: STDOUT: [I] Saving Coffee-Shop.0_lighting.exr: 0.0%
2024/09/12 12:03:36-07:00 ADAPTOR_OUTPUT: STDOUT: [I] Saving Coffee-Shop.0_diffuse.exr: 0.0%
2024/09/12 12:03:36-07:00 ADAPTOR_OUTPUT: STDOUT: [I] Saving Coffee-Shop.0_normals.exr: 0.0%
2024/09/12 12:03:36-07:00 ADAPTOR_OUTPUT: STDOUT: [I] Saving Coffee-Shop.0_depth.exr: 0.0%
2024/09/12 12:03:37-07:00 ADAPTOR_OUTPUT: STDOUT: [I] Saving Coffee-Shop.0.png: 0.0%
2024/09/12 12:03:37-07:00 ADAPTOR_OUTPUT: STDOUT: [I] Saving Coffee-Shop.0_clown.png: 0.0%
2024/09/12 12:03:37-07:00 ADAPTOR_OUTPUT: STDOUT: [I] Saving Coffee-Shop.0.png: 0.0%
2024/09/12 12:03:38-07:00 openjd_fail: Error encountered while running adaptor: KeyShot exited early and did not render successfully, please check render logs. Exit code 3221225477
2024/09/12 12:03:38-07:00 ERROR: Entrypoint failed: openjd_fail: Error encountered while running adaptor: KeyShot exited early and did not render successfully, please check render logs. Exit code 3221225477
```

I also have this in my Keyshot.log file.
```
========== KeyShot 2023.3 (12.2.2.4) at Thu Sep 12 19:02:58 2024 ==========
[C] Cannot open environment image "startup.hdr"
[C] Using environment "startup.hdr" instead
[C] Cannot find "startup.hdr". Expect crash.
[C] Optix error: 7012 (Disk cache database error)
Device : Tesla T4
[C] Could not setup log
```

**Comment by yuanmich2** [comment]
When I was running the job before on CMF, I was creating ksp packages and I can see that they included a file called startup.hdr

However, when I inspect the job attachments being sent with these new renders, I cannot find a startup.hdr.

I don't remember what version of the submitter I was using before, but I remember that I had to manually package things as a ksp and unpack before the scene would render.

**Comment by yuanmich2** [comment]
Update2: Clearing the hdr file and resetting it within my scene fixed this issue. I now get a new error on CMF:

```
2024/09/12 14:10:49-07:00 ADAPTOR_OUTPUT: STDOUT: [I] Saving C:/ProgramData/Amazon/OpenJD/session-80100136458941c1bd6503172ea: 6.7%
2024/09/12 14:10:49-07:00 ADAPTOR_OUTPUT: STDOUT: [I] Saving C:/ProgramData/Amazon/OpenJD/session-80100136458941c1bd6503172ea: 93.3%
2024/09/12 14:10:49-07:00 ADAPTOR_OUTPUT: STDOUT: [I] Saving C:/ProgramData/Amazon/OpenJD/session-80100136458941c1bd6503172ea: 100.0%
2024/09/12 14:11:10-07:00 ADAPTOR_OUTPUT: STDOUT: [W] "GPU Mode" "Unknown error!\nSee log for additional information."
2024/09/12 14:11:10-07:00 ADAPTOR_OUTPUT: STDOUT: [I] GPU initialization: 10.0%
2024/09/12 14:11:10-07:00 ADAPTOR_OUTPUT: STDOUT: [D] Enabling OS sleep
2024/09/12 14:11:10-07:00 ADAPTOR_OUTPUT: STDOUT: [D] Failure
2024/09/12 14:11:10-07:00 ADAPTOR_OUTPUT: STDOUT: [D] Exit? false 0
2024/09/12 14:11:10-07:00 ADAPTOR_OUTPUT: STDOUT: [W] Python errors:
2024/09/12 14:11:10-07:00 ADAPTOR_OUTPUT: STDOUT: Traceback (most recent call last):
2024/09/12 14:11:10-07:00 ADAPTOR_OUTPUT: STDOUT:   File "<string>", line 73, in <module>
2024/09/12 14:11:10-07:00 ADAPTOR_OUTPUT: STDOUT:   File "<string>", line 69, in main
2024/09/12 14:11:10-07:00 ADAPTOR_OUTPUT: STDOUT:   File "C:\Program Files\Python311\Lib\site-packages\openjd\adaptor_runtime_client\base_client_interface.py", line 212, in poll
2024/09/12 14:11:10-07:00 ADAPTOR_OUTPUT: STDOUT:     self._perform_action(action)
2024/09/12 14:11:10-07:00 ADAPTOR_OUTPUT: STDOUT:   File "C:\Program Files\Python311\Lib\site-packages\openjd\adaptor_runtime_client\base_client_interface.py", line 233, in _perform_action
2024/09/12 14:11:10-07:00 ADAPTOR_OUTPUT: STDOUT:     action_func(a.args)
2024/09/12 14:11:10-07:00 ADAPTOR_OUTPUT: STDOUT:   File "C:\Program Files\Python311\Lib\site-packages\deadline\keyshot_adaptor\KeyShotClient\keyshot_handler.py", line 62, in start_render
2024/09/12 14:11:10-07:00 ADAPTOR_OUTPUT: STDOUT:     lux.renderImage(path=output_path, opts=opts, format=self.output_format_code)
2024/09/12 14:11:10-07:00 ADAPTOR_OUTPUT: STDOUT: Exception: Unknown error!
2024/09/12 14:11:10-07:00 ADAPTOR_OUTPUT: STDOUT: See log for additional information.
2024/09/12 14:11:10-07:00 ADAPTOR_OUTPUT: STDOUT: [C] Exiting KeyShot due to uncaught Python exception or script failure!
2024/09/12 14:11:10-07:00 ADAPTOR_OUTPUT: STDOUT: [D] Processing KeyShot close
2024/09/12 14:11:10-07:00 ADAPTOR_OUTPUT: STDOUT: [W] KSettings: Failed to open device for writing!
2024/09/12 14:11:11-07:00 openjd_fail: Error encountered while running adaptor: KeyShot exited early and did not render successfully, please check render logs. Exit code 3221225477
2024/09/12 14:11:11-07:00 ERROR: Entrypoint failed: openjd_fail: Error encountered while running adaptor: KeyShot exited early and did not render successfully, please check render logs. Exit code 3221225477
```

But the job now works on SMF!!!!

**Comment by yuanmich2** [comment]
Update3: disabling render passes fixed the issue on CMF for me
![Coffee-Shop normal-name](https://github.com/user-attachments/assets/b0d7e0b1-69e1-4266-8610-4f4a9833abc3)

**Comment by yuanmich2** [comment]
For me this job failed: https://www.keyshot.com/download/355732/
The exact error is Unable to open "C:/Users/Administrator/Documents/KeyShot 12/thumbnails" for reading so it looks like the issues might be related to certain files not being packaged with the job properly.

It seems very similar to the failure with startup.hdr. I imagine if I could figure out why my project is referencing that path, I could fix it.

**Comment by yuanmich2** [comment]
Attempted some renders again this morning. The original coffee shop scene works 100% of the time for me now, even when downloading from this github issue. I think packaging it up into a ksp again to upload here might have fixed something, which is unfortunate because it means we can no longer reproduce the error as the original download of the file is not available on the Keyshot website anymore.

However, I think it's still an issue that enabling render passes in the Render Settings causes the job to fail.

The second scene: https://www.keyshot.com/download/355732/

continues to fail, but I no longer think the issue has to do with the thumbnails folder because the same "unable to read" error appears in the logs of a successful render of the coffee shop scene. Full logs of a failed render: [Deadline Cloud Farm_Service Managed Jobs_session-3e4e8c149a514e4c9253f3fe0f7744c9.log](https://github.com/user-attachments/files/17193712/Deadline.Cloud.Farm_Service.Managed.Jobs_session-3e4e8c149a514e4c9253f3fe0f7744c9.log)

**Comment by crowecawcaw** [comment]
I downloaded the linked scene and was able to render it successfully using a Keyshot 2024.2 package. We've gotten other reports of sample scenes failing to render with `keyshot_headless` in 2024.1, so I'm guessing this bug is in the same category.

I built a conda package for 2024.2 personally, but it hasn't been published yet for Deadline SMF. I'll comment back when it's live so you can verify that the new version fixes the issue from your side as well.

**Comment by yuanmich2** [comment]
Confirmed with Keyshot that it's an issue with Keyshot and not the submitter/adaptor. Closing this issue.
